---
title: "pca"
author: "Marc Hurtado"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(factoextra)
library(FactoMineR)
```

```{r}
info_barrios_indices <- read.csv(file = "dataTratada/barrios_indices.csv")

info_barrios_indices[is.na(info_barrios_indices)] <- 0
rownames(info_barrios_indices) <- info_barrios_indices$barrio
info_barrios_indices <- select(info_barrios_indices, -barrio)
```

```{r}
res.pca <- PCA(info_barrios_indices, graph = FALSE, ncp = Inf, quali.sup = "Distrito", quanti.sup = c("Universidad", "Hospitales", "Estadio", "Cargadores"))

eig.val <- get_eigenvalue(res.pca)
Vmedia <- 100/nrow(eig.val)
fviz_eig(res.pca, addlabels = TRUE, main = "Eigenvalues") + geom_hline(yintercept = Vmedia, linetype = 2)
```

```{r}
eig.val
K = 3

res.pca <- PCA(info_barrios_indices, graph = FALSE, ncp = K, quali.sup = "Distrito", quanti.sup = c("Universidad", "Hospitales", "Estadio", "Cargadores"))
```

```{r}
misScores = res.pca$ind$coord[,1:K]

miT2 = colSums(t(misScores**2)/eig.val[1:K,1])

I = nrow(info_barrios_indices)

F95 = K*(I**2 - 1)/(I*(I - K)) * qf(0.95, K, I-K)
F99 = K*(I**2 - 1)/(I*(I - K)) * qf(0.99, K, I-K)

plot(1:length(miT2), miT2, type = "p", xlab = "Barrios", ylab = "T2")
abline(h = F95, col = "orange", lty = 2, lwd = 2)
abline(h = F99, col = "red3", lty = 2, lwd = 2)
```

```{r}
anomala <- which(miT2 > F99)
miT2[anomala]
```
```{r}
contribT2 = function (X, scores, loadings, eigenval, observ, cutoff = 2) {
  # X is data matrix and must be centered (or centered and scaled if data were scaled)
  misScoresNorm = t(t(scores**2) / eigenval)
  misContrib = NULL
  for (oo in observ) {
    print(rownames(misScores)[oo])
    print(misScores[oo,])
    misPCs = which(as.numeric(misScoresNorm[oo,]) > cutoff)
    lacontri = sapply(misPCs, function (cc) (misScores[oo,cc]/eigenval[cc])*loadings[,cc]*X[oo,])
    lacontri = rowSums((1*(sign(lacontri) == 1))*lacontri)
    misContrib = cbind(misContrib, lacontri)
  }
  colnames(misContrib) = rownames(misScoresNorm[observ,])
  return(misContrib)
}


barriosCE <- select(info_barrios_indices, -c("Distrito", "Universidad", "Estadio", "Hospitales", "Cargadores"))
barriosCE = scale(barriosCE, center = TRUE, scale = TRUE)
X = as.matrix(barriosCE)
# Calculamos los loadings a partir de las coordenadas de las variables
# ya que la librería FactoMineR nos devuelve los loadings ponderados 
# por la importancia de cada componente principal.

misLoadings = sweep(res.pca$var$coord, 2, sqrt(res.pca$eig[1:K,1]), FUN="/")
# Calculamos las contribuciones
mycontrisT2 = contribT2(X = X, scores = misScores, loadings = misLoadings, 
                        eigenval = eig.val[1:K,1], observ = which.max(miT2),
                        cutoff = 2)
```
```{r}
par(mar = c(10,2.3,3,1))
barplot(mycontrisT2[,1],las=2, #cex.names = 0.5,
        main= "Observación: LA ROQUETA ")
```

```{r}
myE = X - misScores %*% t(misLoadings) 
mySCR = rowSums(myE^2)  

g = var(mySCR)/(2*mean(mySCR))
h = (2*mean(mySCR)^2)/var(mySCR)

chi2lim = g*qchisq(0.95, df = h)
chi2lim99 = g*qchisq(0.99, df = h)


plot(1:length(mySCR), mySCR, type = "l", main = "Distancia al modelo", 
     ylab = "SCR", xlab = "Barrio", ylim = c(0,11))
abline(h = chi2lim, col = "orange", lty = 2, lwd = 2)
abline(h = chi2lim99, col = "red3", lty = 2, lwd = 2)
```


```{r}
barrios_sin_anomala <- info_barrios_indices[-44,]

res.pca1 <- PCA(barrios_sin_anomala, graph = FALSE, ncp = 3, quali.sup = "Distrito", quanti.sup = c("Universidad", "Hospitales", "Estadio", "Cargadores"))

eig.val <- get_eigenvalue(res.pca1)
Vmedia <- 100/nrow(eig.val)
fviz_eig(res.pca1, addlabels = TRUE, main = "Eigenvalues") + geom_hline(yintercept = Vmedia, linetype = 2)
```
```{r}
eig.val
```
```{r}
K = 3
misScores = res.pca1$ind$coord[,1:K]

miT2 = colSums(t(misScores**2)/eig.val[1:K,1])

I = nrow(barrios_sin_anomala)

F95 = K*(I**2 - 1)/(I*(I - K)) * qf(0.95, K, I-K)
F99 = K*(I**2 - 1)/(I*(I - K)) * qf(0.99, K, I-K)

plot(1:length(miT2), miT2, type = "p", xlab = "Barrios", ylab = "T2")
abline(h = F95, col = "orange", lty = 2, lwd = 2)
abline(h = F99, col = "red3", lty = 2, lwd = 2)
```
```{r}
misLoadings = sweep(res.pca1$var$coord, 2, sqrt(res.pca1$eig[1:K,1]), FUN="/")

barriosCE <- select(barrios_sin_anomala, -c("Distrito", "Universidad", "Estadio", "Hospitales", "Cargadores"))
barriosCE = scale(barriosCE, center = TRUE, scale = TRUE)
X = as.matrix(barriosCE)

myE = X - misScores %*% t(misLoadings) 
mySCR = rowSums(myE^2)  

g = var(mySCR)/(2*mean(mySCR))
h = (2*mean(mySCR)^2)/var(mySCR)

chi2lim = g*qchisq(0.95, df = h)
chi2lim99 = g*qchisq(0.99, df = h)


plot(1:length(mySCR), mySCR, type = "l", main = "Distancia al modelo", 
     ylab = "SCR", xlab = "Barrio", ylim = c(0,11))
abline(h = chi2lim, col = "orange", lty = 2, lwd = 2)
abline(h = chi2lim99, col = "red3", lty = 2, lwd = 2)
```
```{r}
fviz_pca_var(res.pca, col.var = "cos2", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE, title = "Variables", axes = c(1,2))
```
```{r}
fviz_pca_var(res.pca, col.var = "cos2", gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"), 
             repel = TRUE, title = "Variables", axes = c(2,3))
```

```{r}
fviz_pca_ind(res.pca, habillage = "Distrito" ,repel = TRUE, title = "Individuos", axes = c(1,2))
```

```{r})
```

```{r})
```

```{r})
```


